print("Challenge 1")
a=int(input())
b=int(input())
print(a+b)
print("Challenge 2")
print("Enter Length of side of square")
c=int(input())
print("The Area of Square is ", c*c)
print ("Challenge 3")
d=float(input())
e=float(input())
print((d+e)/2)
print("Challenge 4")
f=int(input())
g=int(input())
if f>=g:
    print("True")
else:
    print("False")
